from vkwave.bots.utils.keyboards.keyboard import Keyboard, ButtonColor
from random import choice
from json import load

with open('data/cfg.json', 'r', encoding='utf-8') as file:
    data = load(file)
def createKeyboard():
    kb = Keyboard(one_time=False)
    text = data['messageKeyboard']
    colors = (ButtonColor.PRIMARY, ButtonColor.SECONDARY, color=ButtonColor.NEGATIVE, ButtonColor.POSITIVE )
    kb.add_text_button(choice(text), color=choice(colors)
    kb.add_text_button(choice(text), color=choice(colors)
    kb.add_text_button(choice(text), color=choice(colors)
    kb.add_text_button(choice(text), color=choice(colors)
    kb.add_row()
    kb.add_text_button(choice(text), color=choice(colors)
    kb.add_text_button(choice(text), color=choice(colors)
    kb.add_text_button(choice(text), color=choice(colors)
    kb.add_text_button(choice(text), color=choice(colors)
    kb.add_row()
    kb.add_text_button(choice(text), color=choice(colors)
    kb.add_text_button(choice(text), color=choice(colors)
    kb.add_text_button(choice(text), color=choice(colors)
    kb.add_text_button(choice(text), color=choice(colors)
    kb.add_row()
    kb.add_text_button(choice(text), color=choice(colors)
    kb.add_text_button(choice(text), color=choice(colors)
    kb.add_text_button(choice(text), color=choice(colors)
    kb.add_text_button(choice(text), color=choice(colors)
    kb.add_row()
    kb.add_text_button(choice(text), color=choice(colors)
    kb.add_text_button(choice(text), color=choice(colors)
    kb.add_text_button(choice(text), color=choice(colors)
    kb.add_text_button(choice(text), color=choice(colors)
    kb.add_row()
    kb.add_text_button(choice(text), color=choice(colors)
    kb.add_text_button(choice(text), color=choice(colors)
    kb.add_text_button(choice(text), color=choice(colors)
    kb.add_text_button(choice(text), color=choice(colors)
    kb.add_row()
    kb.add_text_button(choice(text), color=choice(colors)
    kb.add_text_button(choice(text), color=choice(colors)
    kb.add_text_button(choice(text), color=choice(colors)
    kb.add_text_button(choice(text), color=choice(colors)
    kb.add_row()
    return kb
